// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdhtkfeqielbgsgbiewm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkaHRrZmVxaWVsYmdzZ2JpZXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzk1ODIsImV4cCI6MjA3MTcxNTU4Mn0.Lm6iORIy_yQDVYSfjsl1VQrdg7vx24OxkggxltYOt-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});